# Project-wide Gradle settings

org.gradle.jvmargs=-Xmx2048M
android.useAndroidX=true

# Android SDK versions
minSdkVersion=28
targetSdkVersion=35
compileSdkVersion=36
ndkVersion=29.0.14206865

# Kotlin
kotlinCodeStyle=official

# Non-transitive R classes
android.nonTransitiveRClass=true

# Termux module dependencies
markwonVersion=4.6.2
